### ISSUE TITLE
Resource certificate?

### ISSUE THREAD

**Issue by markheath** [damienbod/IdentityServer4VueJs#1]
Thanks for providing this sample. Just having a look through the code and noticed that in the resource server startup, you load a certificate, but don't seem to do anything with it. Am I missing something?

https://github.com/damienbod/IdentityServer4VueJs/blob/256519ffe3f6773a6470aec89abdbe7bf75129eb/ResourceServer/Startup.cs#L51

**Comment by damienbod** [comment]
Hi @markheath 

Thanks, yes this is a copy paste bug, I'll remove this. I use to use this to run with the data protection APIs

**Comment by damienbod** [comment]
removed, thanks for the hint
